blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/zenithchron/mint-background-switcher/discussions
    about: Ask questions or share ideas if Discussions are enabled.
